### ISSUE TITLE
Point of Intersection in Plot

### ISSUE THREAD

**Issue by khelfen** [htw-nus/A8_gaussian-elimination#12]
Show the Point of Intersection in the plot. The point of intersection is the solution x

Add another plot into the figure which either shows the single point or a vector directly at the point of intersection of the 3 grids. Something like [this](https://in.mathworks.com/matlabcentral/answers/93623-how-do-i-plot-the-line-of-intersection-between-two-surfaces).

**Comment by mauricio-ocampo** [comment]
[https://github.com/htw-nus/A8_gaussian-elimination/blob/dev/MATLAB/gaussian_elimination_solver.m](url)
After the line 491 I would add the following code:
plot3(X(1),X(2),X(3),'-o','Color','r','MarkerSize',8,'MarkerFaceColor','#FF0000'); 
and then we can see the point of intersection and would add in the Legend of the Plot the Coordinates of the Variable X

**Comment by khelfen** [comment]
![SurfPlot](https://user-images.githubusercontent.com/46815982/88287819-264e3400-ccf3-11ea-99dc-2397cc523e9f.png)

@mauricio-ocampo yes, that worked! 👍
